blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/james-m-jordan/submito-shift-store-access/discussions
    about: Ask general questions here.